{% set name = "anymap" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/anymap-{{ version }}.tar.gz
  sha256: 599711739cfc3bbc3669cfad1062ab52a96f2bfc3e47a6d49d74c9164bff453b

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=64
    - setuptools-scm >=8
    - pip
  run:
    - python  >={{ python_min }}
    - anywidget >=0.9.0
    - ipywidgets >=8.0.0
    - traitlets >=5.0.0

test:
  imports:
    - anymap
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/opengeos/anymap
  summary: A Python package for creating interactive maps with anywidget and JavaScript mapping libraries
  description: A Python package for creating interactive maps with anywidget and JavaScript mapping libraries
  license: MIT
  license_file: LICENSE
  doc_url: https://anymap.gishub.org
  dev_url: https://github.com/opengeos/anymap

extra:
  recipe-maintainers:
    - giswqs
