{% set name = "anymap" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/anymap-{{ version }}.tar.gz
  sha256: 671721799a1c3d82ae6c5241162f5d3deb6fa83bae906d4b682e964ecc52689f

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=64
    - setuptools-scm >=8
    - pip
  run:
    - python  >={{ python_min }}
    - anywidget >=0.9.0
    - geopandas
    - ipyvuetify
    - ipywidgets >=8.0.0
    - numpy
    - pandas
    - psutil
    - pystac-client
    - requests
    - traitlets >=5.0.0
    - xyzservices

test:
  imports:
    - anymap
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/opengeos/anymap
  summary: A Python package for creating interactive maps with anywidget and JavaScript mapping libraries
  description: A Python package for creating interactive maps with anywidget and JavaScript mapping libraries
  license: MIT
  license_file: LICENSE
  doc_url: https://anymap.gishub.org
  dev_url: https://github.com/opengeos/anymap

extra:
  recipe-maintainers:
    - giswqs
